angular.module(['application.services'])
    // define the request notification channel for the pub/sub service
    .factory('requestNotificationChannel', ['$rootScope', function ($rootScope) {
        // private notification messages
        var _EDIT_DATA_ = '_EDIT_DATA_';
        var _DATA_UPDATED_ = '_DATA_UPDATED_';

        // publish edit data notification
        var editData = function (item) {
            $rootScope.$broadcast(_EDIT_DATA_, {item: item});
        };
        //subscribe to edit data notification
        var onEditData = function($scope, handler) {
            $scope.$on(_EDIT_DATA_, function(event, args) {
               handler(args.item);
            });
        };
        // publish data changed notification
        var dataUpdated = function () {
            $rootScope.$broadcast(_DATA_UPDATED_);
        };
        // subscribe to data changed notification
        var onDataUpdated = function ($scope, handler) {
            $scope.$on(_DATA_UPDATED_, function (event) {
                handler();
            });
        };
        // return the publicly accessible methods
        return {
            editData: editData,
            onEditData: onEditData,
            dataUpdated: dataUpdated,
            onDataUpdated: onDataUpdated
        };
    }])
    // define the data service that manages the data
    .factory('dataService', ['requestNotificationChannel', function (requestNotificationChannel) {
        // private data
        var hops = [
            { "_id": { "$oid": "50ae677361d118e3646d7d6c"}, "Name": "Admiral", "Origin": "United Kingdom", "Alpha": 14.75, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "Bittering hops derived from Wye Challenger.  Good high-alpha bittering hops. Use for: Ales Aroma: Primarily for bittering Substitutions: Target, Northdown, Challenger", "Type": "Bittering", "Form": "Pellet", "Beta": 5.6, "HSI": 15.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677361d118e3646d7d6d"}, "Name": "Ahtanum", "Origin": "U.S.", "Alpha": 6.0, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "Distinctive aromatic hops with moderate bittering power from Washington. Use for: Distinctive aroma Substitutes: N/A", "Type": "Aroma", "Form": "Pellet", "Beta": 5.25, "HSI": 30.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677361d118e3646d7d6e"}, "Name": "Amarillo Gold", "Origin": "U.S.", "Alpha": 8.5, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "Unknown origin, but character similar to Cascade. Use for: IPAs, Ales Aroma: Citrus, Flowery Substitutions: Cascade, Centennial", "Type": "Aroma", "Form": "Pellet", "Beta": 6.0, "HSI": 25.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677361d118e3646d7d6f"}, "Name": "Aquila", "Origin": "U.S.", "Alpha": 6.5, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "Aroma hops developed in 1988.  Limited use due to high cohumolone.Used for: Aroma hops Substitutes: ClusterNo longer commercially grown.", "Type": "Aroma", "Form": "Pellet", "Beta": 3.0, "HSI": 35.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677361d118e3646d7d70"}, "Name": "Auscha (Saaz)", "Origin": "Czech Republic", "Alpha": 3.3, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": " Use for: Pilsners and Bohemian style lagers Aroma: Delicate, mild, clean, somewhat floral -- Noble hops Substitute: Tettnanger, LublinExamples: Pulsner Urquell", "Type": "Aroma", "Form": "Pellet", "Beta": 3.5, "HSI": 42.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677361d118e3646d7d71"}, "Name": "Banner", "Origin": "U.S. ", "Alpha": 10.0, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "Bittering hops developed in 1988.  Use largely discontinued due to poor storage.Used for: US style ales Substitutes: Cluster", "Type": "Bittering", "Form": "Pellet", "Beta": 4.0, "HSI": 35.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7d72"}, "Name": "Bramling Cross", "Origin": "United Kingdom", "Alpha": 6.0, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "Developed in 1927 from commercial Goldings and wild hop variety.Best for: ESB, Bitters, Pale Ale Aroma: Mild, fruity, currant aroma. Substitutes: East Kent Goldings, Progress, Whitbred", "Type": "Aroma", "Form": "Pellet", "Beta": 3.0, "HSI": 35.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7d73"}, "Name": "Brewer&apos;s Gold", "Origin": "United Kingdom", "Alpha": 8.0, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "Traditional bittering hops for English ales and heavy German lagers. Aroma: Sharp bittering hop Substitutes: Northern Brewer, Galena, Chinook, EroicaExample: Pete&apos;s Wicked Ale", "Type": "Bittering", "Form": "Pellet", "Beta": 3.7, "HSI": 50.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7d74"}, "Name": "Bullion", "Origin": "United Kingdom", "Alpha": 8.0, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "Used in strong dark english ales, some heavy German lagers. Aroma: Strong, pungent and bitter in flavor.  Blackcurrent flavor. Substitutes: Chinook, Eroica, Brewer&apos;s Gold", "Type": "Bittering", "Form": "Pellet", "Beta": 4.5, "HSI": 50.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7d75"}, "Name": "Cascade", "Origin": "U.S.", "Alpha": 5.5, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": " Use for: American ales and lagers Aroma: Strong spicy, floral, grapefriut character Substitutes: CentennialExamples: Sierra Nevade Pale Ale, Anchor Liberty AleA hops with Northern Brewers Heritage", "Type": "Both", "Form": "Pellet", "Beta": 6.0, "HSI": 50.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7d76"}, "Name": "Centennial", "Origin": "U.S.", "Alpha": 10.0, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": " Use for: General purpose bittering, aroma in American ales and Wheats Aroma: Floral, citrus aroma, spicy, clean bittering flavor Substitutes: Galena, Eroica, Nugget, BullionExamples: Sierra Nevada Celebration Ale, Sierra Nevada Bigfoot", "Type": "Bittering", "Form": "Pellet", "Beta": 4.0, "HSI": 40.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7d77"}, "Name": "Challenger", "Origin": "United Kingdom", "Alpha": 7.5, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "Variant of Northern Brewers heritage Use for: Both aroma and bittering for ales and lagers Aroma: Fruity in flavor, spicy aroma, blends wellSubstitites: N/A", "Type": "Aroma", "Form": "Pellet", "Beta": 4.0, "HSI": 25.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7d78"}, "Name": "Chinook", "Origin": "U.S.", "Alpha": 13.0, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": " Use for: Strong versitile bittering hop for ales, porters, stouts Aroma: Heavy and spicy aroma Substitutes: Galena, Eroica, Nugget, BullionExamples: Sierra Nevada Stout, Sierra Nevada Celebration Ale", "Type": "Bittering", "Form": "Pellet", "Beta": 3.6, "HSI": 20.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7d79"}, "Name": "Cluster", "Origin": "U.S.", "Alpha": 7.0, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": " Use for: General purpose bittering hop Aroma: Sharp aroma and sharp flavor Substitutes: Eroica, Galena", "Type": "Bittering", "Form": "Pellet", "Beta": 4.8, "HSI": 10.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7d7a"}, "Name": "Columbia", "Origin": "United Kingdom", "Alpha": 5.5, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "Sibling of Williamette hops.Used for: All English Ales Aroma: Close to fuggles Substitutes: Fuggles, Williamette", "Type": "Bittering", "Form": "Pellet", "Beta": 3.0, "HSI": 35.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7d7b"}, "Name": "Columbus (Tomahawk)", "Origin": "U.S.", "Alpha": 14.0, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "Engineered Centennial Substitute - High alpha bittering hops. Use for: Bittering, flavor, aroma - IPA, American Pale Ale, Stout, Lager Aroma: Strongly aromatic, but clean tasting bitterness Substitutes: Centennial", "Type": "Bittering", "Form": "Pellet", "Beta": 5.0, "HSI": 40.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7d7c"}, "Name": "Comet", "Origin": "U.S.", "Alpha": 9.5, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "Very bitter hops - use sparingly with other hops Use for: Bittering only Substitutes: N/A", "Type": "Bittering", "Form": "Pellet", "Beta": 4.0, "HSI": 50.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7d7d"}, "Name": "Crystal", "Origin": "U.S.", "Alpha": 3.5, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "Used For: Aroma and finishing hops for Lagers Aroma: Clean, mild, pleasant and slightly spicy Substitutes: Hallertauer, Mount Liberty", "Type": "Aroma", "Form": "Pellet", "Beta": 5.2, "HSI": 50.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7d7e"}, "Name": "Eroica", "Origin": "U.S.", "Alpha": 13.0, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": " Use for: General purpose bittering for ales, porters, stouts Aroma: Clean bittering hop, very bitter Substitutes: Galena, Northern Brewer, ChinookExamples: Blackhoolk Porter, Ballard Bitter", "Type": "Bittering", "Form": "Pellet", "Beta": 4.8, "HSI": 35.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7d7f"}, "Name": "First Gold", "Origin": "United Kingdom", "Alpha": 7.5, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "Dwarf hop with English Golding character Use for: Ales, ESB Aroma: Similar to other Golding varieties, spicy Substitutes: East Kent Goldings, Crystal", "Type": "Both", "Form": "Pellet", "Beta": 3.5, "HSI": 12.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7d80"}, "Name": "Fuggles", "Origin": "United Kingdom", "Alpha": 4.5, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "Used For: General purpose bittering/aroma for English Ales, Dark Lagers Aroma: Mild, soft, grassy, floral aroma Substitute: East Kent Goldings, WilliametteExamples: Samuel Smith&apos;s Pale Ale, Old Peculiar, Thomas Hardy&apos;s Ale", "Type": "Aroma", "Form": "Pellet", "Beta": 2.0, "HSI": 35.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7d81"}, "Name": "Galena", "Origin": "U.S.", "Alpha": 13.0, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": " Use for: General bittering hops for all beers Aroma: Strong, clean, balanced bittering Substitute: Eroica, Northern Brewer, Cluster, ChinookExamples: Catamount Porter", "Type": "Bittering", "Form": "Pellet", "Beta": 7.5, "HSI": 15.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7d82"}, "Name": "Glacier", "Origin": "U.S.", "Alpha": 5.6, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "Genetic mix of at least 8 hops including Elsasser, Brewers Gold, N Brewer, Bullion, Early Green, and others...released in 2000 Use for: Aroma Aroma: Excellent, hoppy Substitutes: N/A", "Type": "Aroma", "Form": "Pellet", "Beta": 7.6, "HSI": 28.5, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7d83"}, "Name": "Goldings, B.C.", "Origin": "Canada", "Alpha": 5.0, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "Used for: Bittering and finishing British ales, bitters, porters and stouts. Aroma: Spicy, floral, rounded mild aroma. Substitutes: East Kent Goldings, Fuggles", "Type": "Aroma", "Form": "Pellet", "Beta": 3.2, "HSI": 40.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7d84"}, "Name": "Goldings, East Kent", "Origin": "United Kingdom", "Alpha": 5.0, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "Used For: General purpose hops for bittering/finishing all British Ales Aroma: Floral, aromatic, earthy, slightly sweet spicy flavor Substitutes: Fuggles, BC GoldingsExamples: Bass Pale Ale, Fullers ESB, Samual Smith&apos;s Pale Ale", "Type": "Aroma", "Form": "Pellet", "Beta": 3.5, "HSI": 35.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7d85"}, "Name": "Green Bullet", "Origin": "New Zealand", "Alpha": 13.5, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "Bittering hops from New Zealand developed in 1972 Use for: Australian-style ales and lagers. Aroma: Floral, raisin aroma. Substitutes: Styrian Goldings", "Type": "Bittering", "Form": "Pellet", "Beta": 7.0, "HSI": 20.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7d86"}, "Name": "Hallertauer", "Origin": "Germany", "Alpha": 4.8, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "Used for: German Ales, German/US/Canadian Lagers, Wheat Beers Aroma: Pleaseant, mild spicy flavor, clean, neutral flavor Substitutes: Crytsal, Liberty, Hallertauer Mittenfrueh", "Type": "Aroma", "Form": "Pellet", "Beta": 4.0, "HSI": 50.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7d87"}, "Name": "Hallertauer Hersbrucker", "Origin": "German", "Alpha": 4.0, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": " Use for: German style lagers and wheat beers Aroma: Noble, pleasant, clean flavor Substitutes: Mt. Hood, Liberty, Hallertauer, MittelfruehExamples: Wheathook Wheaten Ale", "Type": "Aroma", "Form": "Pellet", "Beta": 6.0, "HSI": 25.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7d88"}, "Name": "Hallertauer Mittelfrueh", "Origin": "Germany", "Alpha": 4.0, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "Used for: Continental Lagers, German Ales/Lagers, US Lagers Aroma: Pleasant, assertive, mild herbal aroma Substitutes: Hallertauer, Mt. Hood, Liberty, CrystalExamples: Sam Adams Boston Lager, Sam Adams Boston Lightship", "Type": "Aroma", "Form": "Pellet", "Beta": 4.6, "HSI": 45.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7d89"}, "Name": "Hallertauer, New Zealand", "Origin": "New Zealand", "Alpha": 8.5, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "Hallertauer variant with classic aroma and ability to retain clean taste.Bred from German Hallertauer Mittelfruher Use for: Australian Ales Substitutes: Hallertauer Mittelfruher", "Type": "Both", "Form": "Pellet", "Beta": 3.0, "HSI": 45.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7d8a"}, "Name": "Herald", "Origin": "United Kingdom", "Alpha": 12.0, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "Dwarf variety bred at Wye College (mid 1990s) Use for: Bittering of ales Aroma: Strong, acceptable Substitutes: High alpha English bittering hops", "Type": "Bittering", "Form": "Pellet", "Beta": 5.2, "HSI": 25.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7d8b"}, "Name": "Horizon", "Origin": "U.S.", "Alpha": 12.0, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "Good dual purpose hops derived from Nugget hops in Oregon (1970) Use for: All purpose Ales, Lagers Aroma: Pleasant, Hoppy Substitutions: Magnum or other high alpha hops", "Type": "Bittering", "Form": "Pellet", "Beta": 7.5, "HSI": 30.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7d8c"}, "Name": "Liberty", "Origin": "U.S.", "Alpha": 4.3, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": " Use for: German style lagers Aroma: Fine, mild, slightly spicy flavor Substitutes: Hallertau, Mt hood, CrystalExamples: Pete&apos;s Wicked Lager", "Type": "Aroma", "Form": "Pellet", "Beta": 3.5, "HSI": 50.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7d8d"}, "Name": "Lublin", "Origin": "Poland", "Alpha": 5.0, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "Version of Saaz grown in Poland - also called &quot;Lubelski&quot; Use for: Bohemian lagers and Pilsners Aroma: Noble, mild flavor similar to SaazSubstitites: Saaz, Tettnanger", "Type": "Bittering", "Form": "Pellet", "Beta": 3.0, "HSI": 40.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7d8e"}, "Name": "Magnum", "Origin": "Germany", "Alpha": 14.0, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "German Hallertauer hybrid, widely used in Germany Use for: German ales and lagers Aroma: Good aroma and stable spicy flavor Substitutes: N/A", "Type": "Bittering", "Form": "Pellet", "Beta": 6.5, "HSI": 15.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7d8f"}, "Name": "Mt. Hood", "Origin": "U.S.", "Alpha": 6.0, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": " Use for: European Lagers, finishing Aroma: Mild with a clean aroma, neutral flavor Substitutes: Hallertauer, Liberty, Crystal", "Type": "Aroma", "Form": "Pellet", "Beta": 6.3, "HSI": 40.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7d90"}, "Name": "Newport", "Origin": "U.S.", "Alpha": 11.0, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "Released in Feb. 2002, this hop has a mild aroma and a high alpha-acid content. Similar to Galena, Fuggles, and Nugget, this hop is sure to become very popular.", "Type": "Bittering", "Form": "Pellet", "Beta": 3.0, "HSI": 25.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7d91"}, "Name": "Northdown", "Origin": "United Kingdom", "Alpha": 8.5, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "Variation of Northern Brewers hops grown in England. Use for: Bittering in English ales Aroma: Good bittering, flavor and aroma Substitutes: Northern Brewer", "Type": "Both", "Form": "Pellet", "Beta": 5.5, "HSI": 15.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7d92"}, "Name": "Northern Brewer", "Origin": "Germany", "Alpha": 8.5, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "Also called Hallertauer Northern Brewers Use for: Bittering and finishing both ales and lagers of all kinds Aroma: Fine, dry, clean bittering hop.  Unique flavor. Substitute: Hallertauer Mittelfrueh, HallertauerExamples: Anchor Steam, Old Peculiar, ", "Type": "Both", "Form": "Pellet", "Beta": 4.0, "HSI": 35.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7d93"}, "Name": "Nugget", "Origin": "U.S.", "Alpha": 13.0, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": " Use for: Bittering hops for ales Aroma: Strong bittering, heavy, herbal aroma, spicy Substitutes: ChinookExamples: Sierra Nevada Porter", "Type": "Bittering", "Form": "Pellet", "Beta": 5.0, "HSI": 15.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7d94"}, "Name": "Orion", "Origin": "Germany", "Alpha": 7.25, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "Cross between Perle and an experimental variety Use for: Bittering and aroma Aroma: Pleasant, hoppy Substitutes: Pearle", "Type": "Both", "Form": "Pellet", "Beta": 3.7, "HSI": 17.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7d95"}, "Name": "Pacific Gem", "Origin": "New Zealand", "Alpha": 15.0, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "High alpha smoothcone cross developed at DSIR in 1987. Use for: Bittering - produces a cask-oak woody flavor. Aroma: Pleasant - some blackberry aroma. Substitutes: Bullion", "Type": "Bittering", "Form": "Pellet", "Beta": 8.2, "HSI": 10.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7d96"}, "Name": "Pearle", "Origin": "Germany", "Alpha": 8.0, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": " Use for: General purpose bittering for US and German ales, lagers Aroma: slightly spicy, pleasant aroma, minty Substitutes: Chinook, Galena, Northern BrewerExamples: Sierra Nevada Pale Ale, Pale Bock", "Type": "Bittering", "Form": "Pellet", "Beta": 4.75, "HSI": 15.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7d97"}, "Name": "Phoenix", "Origin": "United Kingdom", "Alpha": 8.0, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "Seedling derived from Wye Yoeman. Use for: Ales Aroma: Similar to Wye Challenger hops Substitutes: Challenger, East Kent Golding, Northdown", "Type": "Bittering", "Form": "Pellet", "Beta": 4.6, "HSI": 10.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7d98"}, "Name": "Pilgrim", "Origin": "United Kingdom", "Alpha": 11.5, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "New variety from Wye College in 2001.  High Selinene content. Use for: Bittering Substitutes: N/A", "Type": "Bittering", "Form": "Pellet", "Beta": 4.7, "HSI": 18.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7d99"}, "Name": "Pioneer", "Origin": "United Kingdom", "Alpha": 9.0, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "Bred from Wye Omega at Wye College in the UK Use for: ESB, English Ales Aroma: Mild English hop aroma Substitutes: East Kent Goldings", "Type": "Both", "Form": "Pellet", "Beta": 3.75, "HSI": 17.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7d9a"}, "Name": "Premiant (Saaz)", "Origin": "Czech Republic", "Alpha": 10.0, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": " Use for: Pilsners and Bohemian style lagers Aroma: Delicate, mild, clean, somewhat floral -- Noble hops Substitute: Tettnanger, LublinExamples: Pulsner Urquell", "Type": "Aroma", "Form": "Pellet", "Beta": 3.5, "HSI": 42.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7d9b"}, "Name": "Pride of Ringwood", "Origin": "Australia", "Alpha": 9.0, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": " Use for: General purpose bittering hops for Australian beers Aroma: Moderate citric aroma, clean bittering flavor Substitutes: Cluster, Galena", "Type": "Bittering", "Form": "Pellet", "Beta": 5.75, "HSI": 45.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7d9c"}, "Name": "Progress", "Origin": "United Kingdom", "Alpha": 6.25, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "Used for: Bittering and aroma in English Ales Aroma: Similar to Fuggles, aromatic, slightly sweet Substitutes: Fuggles", "Type": "Aroma", "Form": "Pellet", "Beta": 2.1, "HSI": 15.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7d9d"}, "Name": "Saaz", "Origin": "Czech Republic", "Alpha": 3.5, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": " Use for: Pilsners and Bohemian style lagers Aroma: Delicate, mild, clean, somewhat floral -- Noble hops Substitute: Tettnanger, LublinExamples: Pulsner Urquell", "Type": "Aroma", "Form": "Pellet", "Beta": 3.5, "HSI": 42.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7d9e"}, "Name": "Santiam", "Origin": "U.S.", "Alpha": 6.0, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "Tripload aroma selection derived from Tettnang and Hallertauer (1997) Use for: Lager, US Pale, Pilsner Substitutions: German Tettnang, Spalt, Spalt Select", "Type": "Aroma", "Form": "Pellet", "Beta": 7.0, "HSI": 35.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7d9f"}, "Name": "Select Spalt", "Origin": "German", "Alpha": 4.75, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "Bred from Hallertauer Mittelfrueh and Spalt in Germany.  Spalt character. Use for: Lager, Pilsner, Noble aroma hop substitute Aroma: Very fine, spalt aroma Substitutes: Spalter, Saaz, Tettnang", "Type": "Aroma", "Form": "Pellet", "Beta": 3.5, "HSI": 17.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7da0"}, "Name": "Simcoe", "Origin": "U.S.", "Alpha": 13.0, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "Pleasant hoppy aroma with low Co-Homulone and high alpha acid content(12-14 percent). Herbal, piney and citrusy.", "Type": "Both", "Form": "Pellet", "Beta": 5.0, "HSI": 25.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7da1"}, "Name": "Sladek (Saaz)", "Origin": "Czech Republic", "Alpha": 7.5, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": " Use for: Pilsners and Bohemian style lagers Aroma: Delicate, mild, clean, somewhat floral -- Noble hops Substitute: Tettnanger, LublinExamples: Pulsner Urquell", "Type": "Aroma", "Form": "Pellet", "Beta": 3.5, "HSI": 42.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7da2"}, "Name": "Sorachi Ace", "Origin": "Japan", "Alpha": 13.7, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "Unknown: Developed at Sapporo. (Brewers Gold x Saaz) Use for: IPAs, Ales Aroma: Lemon Citrus Substitutions: Cascade, Centennial", "Type": "Both", "Form": "Leaf", "Beta": 6.0, "HSI": 25.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7da3"}, "Name": "Southern Cross", "Origin": "New Zealand", "Alpha": 13.0, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "Dual purpose with &quot;European&quot; flavor - from DSIR in 1994 Use for: European flavor bittering/aroma Aroma: Spicy, lemony, slight pine and wood flavors Substitutes: N/A", "Type": "Both", "Form": "Pellet", "Beta": 6.2, "HSI": 15.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7da4"}, "Name": "Spalter", "Origin": "Germany", "Alpha": 4.5, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": " Use for: Traditional German bittering and aroma hops, Altbiers, Lagers Aroma: Mild, pleasant, slight spice Substitute: Saaz, TettnangExamples: Dusseldorf Altbiers", "Type": "Aroma", "Form": "Pellet", "Beta": 4.0, "HSI": 50.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7da5"}, "Name": "Sterling", "Origin": "U.S.", "Alpha": 7.5, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "Flavor is a cross between Saaz and Mt Hood Use for: Lagers, Ales, Pilsners Aroma: Herbal, Spicy, some floral and citrus hints Substitutions: Saaz, Polish Lublin", "Type": "Both", "Form": "Pellet", "Beta": 5.0, "HSI": 15.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7da6"}, "Name": "Sticklebract", "Origin": "New Zealand", "Alpha": 13.5, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "High alpha hops from DSIR research first released in 1972.  Some of the same qualities as Northern Brewer Use for: Dual purpose Aroma: Pine-like with a hint of citrus Substitutes: Northern Brewer", "Type": "Both", "Form": "Pellet", "Beta": 8.0, "HSI": 17.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7da7"}, "Name": "Strisslespalt", "Origin": "France", "Alpha": 4.0, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "Aroma hops used widely in the Alsace area of France. Use for: Pilsner, Lager, Wheat Aroma: Medium intensity, pleasant, hoppy Substitutes: Mt Hood, Crystal, Hallertauer Hersbruck", "Type": "Aroma", "Form": "Pellet", "Beta": 3.8, "HSI": 35.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7da8"}, "Name": "Styrian Goldings", "Origin": "Slovenia", "Alpha": 5.4, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "A seedless version of Fuggles grown in Slovenia Use for: Bittering, finishing for a wide variety of European Beers.   Popular in Europe and the United Kingdom Aroma: Similar to Fuggles: Mild, soft, grassy, floral aroma Substitutes: Fuggles Williamet", "Type": "Aroma", "Form": "Pellet", "Beta": 2.9, "HSI": 30.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7da9"}, "Name": "Summit", "Origin": "U.S.", "Alpha": 18.0, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "Summit is a variety that is appropriately named. The hop boasts alpha acid values between 17-19%. Summit is a dwarf variety grown using a low-trellis system. Because dwarf hops are picked gently in the field, as opposed to their taller cousins, w", "Type": "Bittering", "Form": "Pellet", "Beta": 5.5, "HSI": 25.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7daa"}, "Name": "Sun", "Origin": "U.S.", "Alpha": 14.0, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "A very high alpha bittering hops from Yakima Valley, Washington Use for: Bittering (intense) Aroma: Pleasant, hoppy Substitutes: Other very high alpha US hops", "Type": "Bittering", "Form": "Pellet", "Beta": 5.5, "HSI": 25.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7dab"}, "Name": "Super Alpha", "Origin": "New Zealand", "Alpha": 13.0, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "High alpha hops released in 1976 by DSIR.European in character - clean crisp flavor and resin aroma. Use for: European Styles, General purpose bittering Aroma: Pleasant, resin like aroma Substitutes: N/A", "Type": "Bittering", "Form": "Pellet", "Beta": 8.0, "HSI": 15.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7dac"}, "Name": "Target", "Origin": "United Kingdom", "Alpha": 11.0, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": " Use for: English ales and lagers Aroma: Robust aroma and flavor Substitutes: East Kent Goldings", "Type": "Bittering", "Form": "Pellet", "Beta": 5.0, "HSI": 50.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7dad"}, "Name": "Tettnang", "Origin": "Germany", "Alpha": 4.5, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": " Use for: German ales, lagers and wheat beer Aroma: Noble, mild, fine, slightly spicy Substitutes: Saaz, SpaltExamples: Sam Adams Octoberfest, Anderson Valley ESB", "Type": "Aroma", "Form": "Pellet", "Beta": 3.5, "HSI": 40.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7dae"}, "Name": "Tradition", "Origin": "Germany", "Alpha": 6.0, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "Close descendant of Hallertauer Mittelfrueh bred for high yield. Use for: Lager, Pilsner, Bock, some Weizens Aroma: Fine - similar to Hallertauer Mittelfrueh Substitutes: Hallertauer Mittelfruh, Liberty, Ultra", "Type": "Bittering", "Form": "Pellet", "Beta": 4.5, "HSI": 10.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7daf"}, "Name": "Trschitz (Saaz)", "Origin": "Czech Republic", "Alpha": 3.5, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": " Use for: Pilsners and Bohemian style lagers Aroma: Delicate, mild, clean, somewhat floral -- Noble hops Substitute: Tettnanger, LublinExamples: Pulsner Urquell", "Type": "Aroma", "Form": "Pellet", "Beta": 3.5, "HSI": 42.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7db0"}, "Name": "Ultra", "Origin": "U.S.", "Alpha": 3.0, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "Triploid seedling of the German Hallertauer Variety Use for: Lager, Pilsner, Wheat, Finish hops in ales Aroma: Good to outstanding - some Saaz like qualities Substitutions: Liberty, Hallertauer, Tradition, Saaz", "Type": "Aroma", "Form": "Pellet", "Beta": 3.75, "HSI": 27.5, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7db1"}, "Name": "Vanguard", "Origin": "U.S.", "Alpha": 5.5, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "Diploid seedling made in 1982, released in 1997. Hallertau Mitterfrueh parentage. Use for: European lagers, ales Aroma: Strong aromatic notes Substitutes: Hallertauer Mittelfrueh", "Type": "Aroma", "Form": "Pellet", "Beta": 6.0, "HSI": 18.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7db2"}, "Name": "Warrior", "Origin": "U.S.", "Alpha": 15.0, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "High alpha hops from Yakima Chief Ranches. Also called YCR-5.Best for: Ales, Stouts Substitutes: Nugget", "Type": "Both", "Form": "Pellet", "Beta": 6.0, "HSI": 20.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7db3"}, "Name": "Whitbread Golding Variety (WGV)", "Origin": "United Kingdom", "Alpha": 6.0, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "Derived in England in 1911 from Bates Brewer. Some Golding characteristics, but lacking the full Goldings aroma. Use for: Ales Aroma: Pleasant, hoppy, slightly intense Substitutes: East Kent Goldings, Progress", "Type": "Aroma", "Form": "Pellet", "Beta": 2.5, "HSI": 35.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7db4"}, "Name": "Williamette", "Origin": "U.S.", "Alpha": 5.5, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": " Use for: Finishing American and British Ales Aroma: Mild, grassy, floral, slightly spicy Substitutes: Fuggles, E.K. GoldingsExamples: Sierra Nevada Porter, Ballard Bitter", "Type": "Aroma", "Form": "Pellet", "Beta": 3.5, "HSI": 40.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""} ,
            { "_id": { "$oid": "50ae677461d118e3646d7db5"}, "Name": "Zeus", "Origin": "U.S.", "Alpha": 14.0, "Amount": 0.0, "Use": "Boil", "Time": 0.0, "Notes": "Super high alpha bittering hops developed in the Yakima Valley, WA Use for: Bittering, intense aroma Aroma: Aromatic, pleasant Substitutes: Other high alpha hops", "Type": "Bittering", "Form": "Pellet", "Beta": 5.0, "HSI": 45.0, "Humulene": 0.0, "Caryophyllene": 0.0, "Cohumulone": 0.0, "Myrcene": 0.0, "Substitutes": ""}
        ];
        // sends notification that data has been updated
        var saveHop = function(hop) {
            requestNotificationChannel.dataUpdated();
        };
        // removes the item from the array and sends a notification that data has been updated
        var deleteHop = function(hop) {
            for(var i = 0; i < hops.length; i++) {
                if(hops[i]._id.$oid === hop._id.$oid) {
                    hops.splice(i, 1);
                    requestNotificationChannel.dataUpdated();
                    return;
                }
            };
        };
        // internal function to generate a random number guid generation
        var S4 = function() {
            return (((1+Math.random())*0x10000)|0).toString(16).substring(1);
        };
        // generates a guid for adding items to array
        var guid = function () {
          return (S4() + S4() + "-" + S4() + "-4" + S4().substr(0,3) + "-" + S4() + "-" + S4() + S4() + S4()).toLowerCase();
        };
        // function to add a hop to the array and sends a notification that data has been updated
        var addHop = function(hop) {
            hops.id.$oid = guid();
            hops.push(hop);
            requestNotificationChannel.dataUpdated();
        };
        // returns the array of hops
        var getHops = function() {
            return hops;
        };
        // returns a specific hop with the given id
        var getHop = function(id) {
            for(var i = 0; i < hops.length; i++) {
                if(hops[i]._id.$oid === id) {
                    return hops[i];
                }
            };
        };
        // return the publicly accessible methods
        return {
            getHops: getHops,
            getHop: getHop,
            saveHop: saveHop,
            deleteHop: deleteHop,
            addHop: addHop
        }
    }]);






